import { Team } from './types';

export const TEAMS: Team[] = [
  {
    id: 'team-ui',
    label: 'Team 01',
    number: '06',
    navLabel: 'UI / Design',
    projects: [
      {
        id: 'ui-1',
        name: 'Redesign of Creative Cloud Home',
        author: 'Mia Tanaka',
        role: 'UX Design Intern',
        tag: 'UX Research',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'Figma, React',
        impact: 'High',
        desc: 'A comprehensive redesign of the Creative Cloud home dashboard, focusing on reducing cognitive load and surfacing personalized content. Introduces a new information architecture and modular card system.',
        tags: ['Figma', 'Prototyping', 'User Testing', 'Design System'],
      },
      {
        id: 'ui-2',
        name: 'Accessible Color Token System',
        author: 'Ravi Sharma',
        role: 'UI Design Intern',
        tag: 'Accessibility',
        status: 'Completed',
        timeline: 'Jun – Jul 2026',
        stack: 'Tokens Studio, CSS',
        impact: 'Critical',
        desc: 'Building an accessible color token system that passes WCAG 2.2 AA across all Adobe product surfaces. Includes automated contrast checking tooling integrated with Figma.',
        tags: ['Tokens', 'WCAG', 'Automation'],
      },
      {
        id: 'ui-3',
        name: 'Component Library v4.0',
        author: 'Lena Fischer',
        role: 'Frontend Intern',
        tag: 'Design System',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'React, Storybook',
        impact: 'High',
        desc: 'A major revision of the internal Spectrum component library, adding 40+ new components and migrating existing ones to CSS custom properties for better theming support.',
        tags: ['React', 'Storybook', 'Spectrum', 'CSS'],
      },
      {
        id: 'ui-4',
        name: 'Onboarding Flow Redesign',
        author: 'Kai Okafor',
        role: 'Product Design Intern',
        tag: 'UX',
        status: 'In Review',
        timeline: 'Jun – Jul 2026',
        stack: 'Figma, Maze',
        impact: 'Medium',
        desc: 'Redesigning the first-time user onboarding flow for Adobe Express, tested with 120 participants. New flow reduces time-to-first-creation from 8 minutes to 2.4 minutes.',
        tags: ['Onboarding', 'Express', 'Research'],
      },
      {
        id: 'ui-5',
        name: 'Motion Design Guidelines',
        author: 'Sofia Reyes',
        role: 'Motion Design Intern',
        tag: 'Motion',
        status: 'Completed',
        timeline: 'May – Jul 2026',
        stack: 'After Effects, Lottie',
        impact: 'Medium',
        desc: 'Establishing a comprehensive set of motion design principles and micro-interaction specifications for all Adobe web properties, with Lottie export tooling.',
        tags: ['Animation', 'Lottie', 'Guidelines'],
      },
      {
        id: 'ui-6',
        name: 'Dark Mode Audit & Fixes',
        author: 'James Li',
        role: 'UI Engineering Intern',
        tag: 'Theming',
        status: 'Completed',
        timeline: 'Jun – Jun 2026',
        stack: 'CSS, TypeScript',
        impact: 'High',
        desc: 'Full dark mode audit across 14 Adobe product surfaces, resolving 340+ contrast and theming issues. Implemented automated regression tests to prevent future regressions.',
        tags: ['Dark Mode', 'CSS', 'Testing'],
      },
    ],
  },
  {
    id: 'team-data',
    label: 'Team 02',
    number: '05',
    navLabel: 'Data & Analytics',
    projects: [
      {
        id: 'data-1',
        name: 'Creative Insights Dashboard',
        author: 'Priya Menon',
        role: 'Data Science Intern',
        tag: 'Visualization',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'D3.js, Python',
        impact: 'High',
        desc: 'Real-time analytics dashboard for Adobe Creative Cloud usage patterns. Surfaces insights on feature adoption, user journeys, and churn prediction using ML-based scoring.',
        tags: ['D3.js', 'Python', 'ML', 'Dashboard'],
      },
      {
        id: 'data-2',
        name: 'Churn Prediction Model v2',
        author: 'Daniel Park',
        role: 'ML Engineering Intern',
        tag: 'Machine Learning',
        status: 'Completed',
        timeline: 'May – Jul 2026',
        stack: 'Python, XGBoost',
        impact: 'Critical',
        desc: 'A second-generation churn prediction model for Creative Cloud subscribers, achieving 91% precision on 30-day churn with a new feature set based on in-app engagement signals.',
        tags: ['XGBoost', 'Feature Engineering', 'Prediction'],
      },
      {
        id: 'data-3',
        name: 'A/B Test Framework',
        author: 'Amara Diallo',
        role: 'Data Engineering Intern',
        tag: 'Experimentation',
        status: 'In Review',
        timeline: 'Jun – Aug 2026',
        stack: 'Spark, Redshift',
        impact: 'High',
        desc: 'End-to-end A/B testing framework enabling product teams to design, run, and analyze experiments at scale. Reduces experiment turnaround time from 2 weeks to 3 days.',
        tags: ['Spark', 'Redshift', 'Statistics', 'ETL'],
      },
      {
        id: 'data-4',
        name: 'Usage Attribution Pipeline',
        author: 'Yuki Sato',
        role: 'Data Engineering Intern',
        tag: 'Data Pipeline',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'Airflow, dbt',
        impact: 'Medium',
        desc: 'A new data attribution pipeline that accurately credits product features to user conversion events, enabling more confident product investment decisions.',
        tags: ['Airflow', 'dbt', 'Attribution'],
      },
      {
        id: 'data-5',
        name: 'NPS Sentiment Analyzer',
        author: 'Carlos Vega',
        role: 'NLP Intern',
        tag: 'NLP',
        status: 'Completed',
        timeline: 'Jun – Jul 2026',
        stack: 'BERT, FastAPI',
        impact: 'Medium',
        desc: 'Fine-tuned BERT model for classifying sentiment and extracting themes from NPS survey responses at scale, replacing manual tagging and enabling trend detection.',
        tags: ['BERT', 'NLP', 'FastAPI', 'Survey Analysis'],
      },
    ],
  },
  {
    id: 'team-workfront',
    label: 'Team 03',
    number: '05',
    navLabel: 'Workfront',
    projects: [
      {
        id: 'wf-1',
        name: 'Workflow Automation Engine',
        author: 'Aisha Kimani',
        role: 'Backend Engineering Intern',
        tag: 'Automation',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'Java, Kubernetes',
        impact: 'Critical',
        desc: 'A rule-based automation engine for Workfront that allows project managers to define conditional workflow triggers, reducing manual task assignment by an estimated 60%.',
        tags: ['Java', 'K8s', 'Automation', 'Workflow'],
      },
      {
        id: 'wf-2',
        name: 'Resource Load Balancer',
        author: 'Tom Müller',
        role: 'Product Engineering Intern',
        tag: 'Resource Mgmt',
        status: 'In Review',
        timeline: 'Jun – Jul 2026',
        stack: 'TypeScript, GraphQL',
        impact: 'High',
        desc: 'Intelligent resource allocation tool that analyzes team capacity and project deadlines to surface over-allocation risks and suggest rebalancing options.',
        tags: ['GraphQL', 'TypeScript', 'Resource Planning'],
      },
      {
        id: 'wf-3',
        name: 'Gantt Chart Revamp',
        author: 'Nina Patel',
        role: 'Frontend Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'May – Jul 2026',
        stack: 'React, Canvas API',
        impact: 'High',
        desc: 'A full performance rewrite of the Workfront Gantt chart using Canvas API, achieving 10x rendering speed improvement for projects with 1,000+ tasks.',
        tags: ['Canvas API', 'React', 'Performance'],
      },
      {
        id: 'wf-4',
        name: 'Integration Hub',
        author: 'Ethan Brooks',
        role: 'Integrations Intern',
        tag: 'Integrations',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'Node.js, Webhooks',
        impact: 'Medium',
        desc: 'A centralized integration hub connecting Workfront to Slack, Jira, and GitHub, enabling bi-directional task sync and automated status updates.',
        tags: ['Node.js', 'Slack', 'Jira', 'GitHub'],
      },
      {
        id: 'wf-5',
        name: 'Mobile App Offline Mode',
        author: 'Fatima Al-Hassan',
        role: 'Mobile Intern',
        tag: 'Mobile',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'React Native, SQLite',
        impact: 'Medium',
        desc: 'Full offline capability for the Workfront mobile app, including optimistic UI updates and intelligent sync resolution when connectivity is restored.',
        tags: ['React Native', 'SQLite', 'Offline', 'Sync'],
      },
    ],
  },
  {
    id: 'team-content',
    label: 'Team 04',
    number: '05',
    navLabel: 'Content',
    projects: [
      {
        id: 'ct-1',
        name: 'AI Content Brief Generator',
        author: 'Lucas Martin',
        role: 'Content Tech Intern',
        tag: 'AI-Assisted',
        status: 'Completed',
        timeline: 'Jun – Jul 2026',
        stack: 'Claude API, Next.js',
        impact: 'High',
        desc: 'An AI-powered brief generation tool for content teams that synthesizes brand guidelines, audience data, and campaign goals into structured creative briefs in under 30 seconds.',
        tags: ['AI', 'Claude API', 'Next.js', 'Content Strategy'],
      },
      {
        id: 'ct-2',
        name: 'Global Translation Pipeline',
        author: 'Yuna Kim',
        role: 'Localization Intern',
        tag: 'Localization',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'Python, Phrase TMS',
        impact: 'Critical',
        desc: 'Automated localization pipeline for Adobe marketing content, supporting 26 languages with human-in-the-loop review for high-sensitivity strings.',
        tags: ['Localization', 'Python', 'i18n', 'Translation'],
      },
      {
        id: 'ct-3',
        name: 'Content Performance Tracker',
        author: 'Omar Hassan',
        role: 'Content Analytics Intern',
        tag: 'Analytics',
        status: 'In Review',
        timeline: 'Jun – Aug 2026',
        stack: 'Looker, BigQuery',
        impact: 'Medium',
        desc: "A real-time content performance dashboard tracking engagement, SEO ranking, and conversion metrics across Adobe's global web presence.",
        tags: ['Looker', 'BigQuery', 'SEO', 'Analytics'],
      },
      {
        id: 'ct-4',
        name: 'Brand Voice Style Guide',
        author: 'Emma Clarke',
        role: 'Brand Content Intern',
        tag: 'Brand',
        status: 'Completed',
        timeline: 'May – Jun 2026',
        stack: 'Notion, Figma',
        impact: 'Medium',
        desc: 'A comprehensive, interactive brand voice style guide with before/after examples, tone calibration tools, and integration with writing assistance plugins.',
        tags: ['Brand Strategy', 'Writing', 'Style Guide'],
      },
      {
        id: 'ct-5',
        name: 'Video Metadata Automation',
        author: 'Raj Gupta',
        role: 'Media Tech Intern',
        tag: 'Media Ops',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'Python, Adobe Premiere API',
        impact: 'Medium',
        desc: "Automated tagging and metadata enrichment for Adobe's video content library, using computer vision and audio transcription to accelerate publishing workflows.",
        tags: ['Computer Vision', 'Metadata', 'Premiere API', 'Automation'],
      },
    ],
  },
  {
    id: 'team-platform',
    label: 'Team 05',
    number: '06',
    navLabel: 'Platform',
    projects: [
      {
        id: 'pl-1',
        name: 'Edge CDN Optimization',
        author: 'Alex Chen',
        role: 'Infrastructure Intern',
        tag: 'Performance',
        status: 'Completed',
        timeline: 'Jun – Jul 2026',
        stack: 'Cloudflare Workers, Rust',
        impact: 'Critical',
        desc: "Optimizing Adobe's global CDN edge configuration using Cloudflare Workers, achieving 40% reduction in global P95 latency for static asset delivery.",
        tags: ['CDN', 'Edge Computing', 'Rust', 'Cloudflare'],
      },
      {
        id: 'pl-2',
        name: 'Developer Portal Rebuild',
        author: 'Sara Johnson',
        role: 'DevEx Intern',
        tag: 'Developer Tools',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'Next.js, Contentful',
        impact: 'High',
        desc: 'Full rebuild of the Adobe Developer Portal with improved navigation, interactive API explorer, code sandbox environments, and semantic search.',
        tags: ['Next.js', 'Developer Experience', 'Docs', 'Search'],
      },
      {
        id: 'pl-3',
        name: 'Auth0 Migration',
        author: 'Marcus Webb',
        role: 'Security Intern',
        tag: 'Security',
        status: 'Completed',
        timeline: 'May – Jul 2026',
        stack: 'Auth0, TypeScript',
        impact: 'Critical',
        desc: 'Platform-wide migration of authentication services to Auth0, consolidating 12 separate auth implementations and enabling Universal Login across all Adobe web properties.',
        tags: ['Auth0', 'Security', 'SSO', 'TypeScript'],
      },
      {
        id: 'pl-4',
        name: 'Observability Stack v2',
        author: 'Hina Tanaka',
        role: 'SRE Intern',
        tag: 'Observability',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'OpenTelemetry, Grafana',
        impact: 'High',
        desc: 'Upgrading the platform observability stack to OpenTelemetry standards, adding distributed tracing across 80+ microservices with custom Grafana dashboards.',
        tags: ['OpenTelemetry', 'Grafana', 'Tracing', 'SRE'],
      },
      {
        id: 'pl-5',
        name: 'CI/CD Pipeline Templates',
        author: 'Ben Osei',
        role: 'DevOps Intern',
        tag: 'DevOps',
        status: 'Completed',
        timeline: 'Jun – Jul 2026',
        stack: 'GitHub Actions, Terraform',
        impact: 'Medium',
        desc: 'Standardized CI/CD pipeline templates for Adobe engineering teams, reducing pipeline setup time from days to under 30 minutes while enforcing security scanning and testing gates.',
        tags: ['GitHub Actions', 'Terraform', 'DevOps', 'Templates'],
      },
      {
        id: 'pl-6',
        name: 'Cost Attribution Dashboard',
        author: 'Mei Lin',
        role: 'FinOps Intern',
        tag: 'FinOps',
        status: 'In Review',
        timeline: 'Jun – Aug 2026',
        stack: 'AWS Cost Explorer, Looker',
        impact: 'High',
        desc: 'A FinOps dashboard that attributes cloud infrastructure costs to product teams and features, enabling data-driven infrastructure investment decisions.',
        tags: ['AWS', 'FinOps', 'Cost Management', 'Looker'],
      },
    ],
  },
  {
    id: 'team-ai',
    label: 'Team 06',
    number: '05',
    navLabel: 'AI & ML',
    projects: [
      {
        id: 'ai-1',
        name: 'Generative Fill API Wrapper',
        author: 'Ivan Petrov',
        role: 'ML Engineering Intern',
        tag: 'Generative AI',
        status: 'Completed',
        timeline: 'Jun – Jul 2026',
        stack: 'Python, FastAPI',
        impact: 'High',
        desc: "High-performance API wrapper for Adobe Firefly's Generative Fill capability, adding request batching, caching, and quality-scoring to power third-party integrations.",
        tags: ['Firefly', 'Generative AI', 'FastAPI', 'API Design'],
      },
      {
        id: 'ai-2',
        name: 'Content Moderation Model',
        author: 'Zoe Adams',
        role: 'Trust & Safety Intern',
        tag: 'Safety',
        status: 'In Review',
        timeline: 'Jun – Aug 2026',
        stack: 'PyTorch, CLIP',
        impact: 'Critical',
        desc: 'A multi-modal content moderation model for AI-generated assets, combining CLIP-based visual classification with policy rule enforcement to flag violations at 99.2% precision.',
        tags: ['CLIP', 'PyTorch', 'Moderation', 'Safety'],
      },
      {
        id: 'ai-3',
        name: 'Prompt Optimization Toolkit',
        author: 'Arjun Nair',
        role: 'AI Product Intern',
        tag: 'LLM Tooling',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'LangChain, Python',
        impact: 'Medium',
        desc: 'A systematic prompt evaluation and optimization toolkit that runs structured experiments across model variants and prompt templates, reporting on quality and cost tradeoffs.',
        tags: ['LangChain', 'Prompting', 'Evaluation', 'LLM'],
      },
      {
        id: 'ai-4',
        name: 'Style Transfer Pipeline',
        author: 'Chiara Romano',
        role: 'Computer Vision Intern',
        tag: 'Computer Vision',
        status: 'Completed',
        timeline: 'May – Jul 2026',
        stack: 'PyTorch, ONNX',
        impact: 'High',
        desc: 'Real-time style transfer pipeline for Photoshop integration, optimized with ONNX Runtime to run inference on consumer GPUs at under 200ms per image.',
        tags: ['ONNX', 'PyTorch', 'Style Transfer', 'Photoshop'],
      },
      {
        id: 'ai-5',
        name: 'Embedding-Based Asset Search',
        author: 'Kwame Asante',
        role: 'Search Intern',
        tag: 'Semantic Search',
        status: 'In Progress',
        timeline: 'Jun – Aug 2026',
        stack: 'FAISS, Python, React',
        impact: 'High',
        desc: 'Replacing keyword-based asset search in Adobe Stock with a vector embedding approach, enabling semantic and multi-modal queries that improve relevance by 37%.',
        tags: ['FAISS', 'Embeddings', 'Adobe Stock', 'Search'],
      },
    ],
  },
];

export const AVATAR_COLORS = [
  { bg: 'rgba(225,37,27,0.2)', color: '#e1251b' },
  { bg: 'rgba(37,99,235,0.2)', color: '#60a5fa' },
  { bg: 'rgba(5,150,105,0.2)', color: '#34d399' },
  { bg: 'rgba(217,119,6,0.2)', color: '#fbbf24' },
  { bg: 'rgba(139,92,246,0.2)', color: '#a78bfa' },
  { bg: 'rgba(236,72,153,0.2)', color: '#f472b6' },
] as const;