import { Team } from './types';

export const TEAMS: Team[] = [
  {
    id: 'team-ui',
    label: 'Team 01',
    number: '03',
    navLabel: 'UI',
    projects: [
      {
        id: 'ui-1',
        name: 'Nirmit',
        author: 'Achindra Sharma',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Typescript, Python FastAPI',
        impact: 'High',
        desc: 'Nirmit is a culturally-aware design partner that bridges the gap between expensive professional firms and local contractors for Indian homeowners. By understanding the nuances of Indian domestic life, it transforms a simple conversation into personalized, 3D room visions that users can refine through natural dialogue. The experience provides instant cost clarity and a detailed execution plan, making high-quality, custom home design accessible and achievable.',
        link: 'https://nirmit-project.vercel.app',
        tags: [],
      },
      {
        id: 'ui-2',
        name: 'FinPath - AI Financial Planner',
        author: 'Daniel Paul',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Typescript, Python FastAPI',
        impact: 'High',
        desc: 'FinPath is a personal finance app that helps users track their income and expenses, set and allocate financial goals with auto-generated month-by-month plans, simulate debt payoff using avalanche or snowball strategies, visualize cash flow , monitor their financial health with a composite score, explore what-if scenarios, and chat with an AI assistant named Penny for financial insights.',
        link: 'https://finpathuiuxdesign-rsbi.vercel.app/',
        tags: [],
      },
      {
        id: 'ui-3',
        name: 'Lume Corp',
        author: 'Shreeya Bajpai',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Javascript',
        impact: 'High',
        desc: 'An AI-integrated corporate event planning platform designed for an immersive experience of the planning flow, with 2D setup visualiser.',
        link: 'https://adobe-my.sharepoint.com/:p:/p/shreeyab/IQBY68a8_KEqTbnjUwTt0QBYAR6KiuC8PByMZLEG8R4PMDA?e=AXwYpH',
        tags: [],
      },
    ],
  },
  {
    id: 'team-data',
    label: 'Team 02',
    number: '01',
    navLabel: 'DATA',
    projects: [
      {
        id: 'data-1',
        name: 'AEP QueryGen',
        author: 'Anamaya Saraogi, Kanika Jain',
        role: 'Technical Consultant Intern',
        tag: 'Visualization',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python FastAPI, React',
        impact: 'High',
        desc: 'Built a utility tool leveraging LLM and RAG to automate segment validation on Adobe Experience Platform, significantly reducing manual effort.',
        link: '',
        tags: [],
      },
      {
        id: 'data-2',
        name: 'Coworker Case Study',
        author: 'Rhitam Bhuiya',
        role: 'Technical Consultant Intern',
        tag: 'Research',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: '',
        impact: 'High',
        desc: '',
        link: '',
        tags: [],
      },
      {
        id: 'data-3',
        name: 'ATLAS AI - QA Automator Enhancement',
        author: 'Anushree Agrawal, Ruddhida R',
        role: 'Technical Consultant Intern',
        tag: 'Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: '',
        impact: 'High',
        desc: '',
        link: '',
        tags: [],
      },
      {
        id: 'data-4',
        name: 'Gandalf - AEP Trainer Agent',
        author: 'Yash Bhatt',
        role: 'Technical Consultant Intern',
        tag: 'Enablement',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: '',
        impact: 'High',
        desc: 'Interactive Learning Agent for Enablement and Cross Learning across Experience Platform and ACS Technologies.',
        link: '',
        tags: [],
      },
      {
        id: 'data-5',
        name: 'Artemis',
        author: 'Stuti Mishra',
        role: 'Technical Consultant Intern',
        tag: 'Data',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: '',
        impact: 'High',
        desc: '',
        link: '',
        tags: [],
      },
    ],
  },
  {
    id: 'team-workfront',
    label: 'Team 03',
    number: '02',
    navLabel: 'WORKFRONT',
    projects: [
      {
        id: 'wf-1',
        name: 'Audit Automation',
        author: 'Namratha R',
        role: 'Technical Consultant Intern',
        tag: 'Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Workfront Core, Workfront Fusion, Claude (LLM), Webhooks, JSON Processing, Prompt Engineering, Reporting and Canvas Dashobard',
        impact: 'Critical',
        desc: 'Developed an AI-powered Audit Automation solution to automate audit assessments, gap identification, risk analysis, escalation tracking, action item generation, and project RAG reporting. The platform transforms audit conversations into structured deliverables, findings, recommendations, and executive dashboard insights for governance and portfolio visibility. ',
        link: '',
        tags: [],
      },
      {
        id: 'wf-2',
        name: 'IntelliMatch AI',
        author: 'Sachin D.',
        role: 'Technical Consultant Intern',
        tag: 'Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: ' Ollama (Local LLM Runtime), Mistral (LLM Model), SBERT DL Model, Python FastAPI, JSON Data Pipelines, Workfront Core, Workfront Fusion, Ngrok, Streamlit, HTML',
        impact: 'Critical',
        desc: 'A hybrid agentic system for intelligent project allocation and workforce decisions, that brings decision intelligence to project allocation, enabling structured, explainable, and data-driven staffing decisions.',
        link: '',
        tags: [],
      },
      {
        id: 'wf-3',
        name: 'Fusion MCP Server',
        author: 'Mihira Gupta',
        role: 'Technical Consultant Intern',
        tag: 'Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: '',
        impact: 'High',
        desc: '',
        link: '',
        tags: [],
      },
    ],
  },
  {
    id: 'team-content',
    label: 'Team 04',
    number: '02',
    navLabel: 'CONTENT',
    projects: [
      {
        id: 'ct-1',
        name: 'Adokicks',
        author: 'A R Rajeev Chandar',
        role: 'Technical Consultant Intern',
        tag: 'AI-Assisted',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'EDS, HTML, CSS, Javascript',
        impact: 'High',
        desc: 'AdoKicks is a modern e-commerce footwear platform built using Adobe Experience Manager and Edge Delivery Services principles to deliver a fast, scalable, and seamless shopping experience.',
        link: '',
        tags: [],
      },
      {
        id: 'ct-2',
        name: 'Global Translation Pipeline',
        author: 'Sudeepa Santhanam',
        role: 'Technical Consultant Intern',
        tag: 'Localization',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'EDS, HTML, CSS, Javascript',
        impact: 'Critical',
        desc: 'Automated localization pipeline for Adobe marketing content, supporting 26 languages with human-in-the-loop review for high-sensitivity strings.',
        link: '',
        tags: [],
      },
      {
        id: 'ct-3',
        name: 'SkillHire',
        author: 'Vanshita Tripathi',
        role: 'Technical Consultant Intern',
        tag: 'Marketplace',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'HTML, CSS, JS, EDS',
        impact: 'High',
        desc: 'SkillHire is a two-sided freelance marketplace built on Adobe Edge Delivery Services. Clients post projects, browse freelancers, and send hire invites. Freelancers apply to projects, counter offers, and manage proposals — all via a localStorage-powered dashboard. Features include role-based auth, paywall upgrades, profile setup, and a full hire-to-acceptance workflow.',
        link: 'https://github.com/Horizon2553/skill-eds',
        tags: [],
      },
      {
        id: 'ct-4',
        name: 'HackVerse',
        author: 'Shruti Gupta',
        role: 'Technical Consultant Intern',
        tag: 'EDS Migration',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Vanilla JS',
        impact: 'High',
        desc: 'A hackathon discovery website built in vanilla JS and replicated in Adobe Edge Delivery Services.',
        link: 'https://hackathon-lilac-chi.vercel.app',
        tags: [],
      },
      {
        id: 'ct-5',
        name: 'RE:WEAR',
        author: 'Pooja Bhatia',
        role: 'Technical Consultant Intern',
        tag: 'EDS Migration',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'HTML, CSS, JavaScript',
        impact: 'High',
        desc: 'RE:WEAR is a thrift and vintage fashion marketplace, originally built in plain HTML, CSS and JavaScript and migrated onto Adobe Edge Delivery Services.',
        link: 'https://github.com/PoojaBhatia16/Eds',
        tags: [],
      },
      {
        id: 'ct-6',
        name: 'Craftora',
        author: 'Radha Goyal',
        role: 'Technical Consultant Intern',
        tag: 'E-commerce',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'AEM',
        impact: 'High',
        desc: "An e-commerce platform where users can customise their product, preview it, and buy. Built using Adobe's EDS and da.live for content authoring.",
        link: 'https://github.com/goelradha12/craftora-eds',
        tags: [],
      },
      {
        id: 'ct-7',
        name: 'HerbAtlas',
        author: 'Gadesina Dheeraj Reddy',
        role: 'Technical Consultant Intern',
        tag: 'E-commerce',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'HTML, CSS, JavaScript, da.live',
        impact: 'High',
        desc: 'A responsive medicinal herb e-commerce website with search, filters, cart, and checkout, migrated to Adobe Edge Delivery Services (EDS) using 19 reusable content blocks and da.live, with Lighthouse scores of 98–100 across Performance, Accessibility, and Best Practices.',
        link: 'https://github.com/DHEERAJREDDY-12/herbatlas-eds',
        tags: [],
      },
      {
        id: 'ct-8',
        name: 'Vaultora',
        author: 'Evelyn Jessica',
        role: 'Technical Consultant Intern',
        tag: 'E-commerce',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'JS, CSS, EDS',
        impact: 'High',
        desc: 'Vaultora is an ultra-premium, sustainable live auction terminal for the alternative asset marketplace, bridging conscious collectors with authenticated luxury commodities across fine timepieces, heritage jewelry, classic art, and elite electronics.',
        link: '',
        tags: [],
      },
    ],
  },
  {
    id: 'team-dacoe',
    label: 'Team 05',
    number: '02',
    navLabel: 'DACoE',
    projects: [
      {
        id: 'pl-1',
        name: 'Retail Insight Orchestrator',
        author: 'Shambhavi Sinha',
        role: 'Technical Consultant Intern',
        tag: 'Performance',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python, AEP',
        impact: 'Critical',
        desc: "This project is a retail insight orchestration layer built on top of Customer Journey Analytics (via CJA MCP). It takes a business question in natural language, understands the retail intent, maps it to the right metrics and dimensions, and generates a structured analysis workflow instead of making the user manually figure out what to ask.",
        link: 'https://adobe-my.sharepoint.com/:p:/p/shamsinha/IQDM2pbHw4dATaTHnuxWXy47AQ-nlceHPlhJCbeEl-EpsDE?e=CfVa70',
        tags: [],
      },
      {
        id: 'pl-2',
        name: 'Agent Evaluation Harness',
        author: 'Yanish Rai',
        role: 'Technical Consultant Intern',
        tag: 'Developer Tools',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python, React',
        impact: 'High',
        desc: `Given (a) an AEP dataset and (b) a set of business use cases, automatically generates a tiered prompt suite for the Data Insights Agent, executes those prompts against the live agent in AEP, computes the ground-truth answer directly from the underlying data, scores the agent's responses against ground truth, and produces a reliability report with failure mode analysis.`,
        link: 'https://adobe-my.sharepoint.com/:p:/p/yanishr/IQAXuRVmHUJWR4BZRSOhihq5AXjqCVG-nbpgWwRUmsoMf7U?e=Y4fmRa',
        tags: [],
      },
    ],
  },
  {
    id: 'team-sbc',
    label: 'Team 07',
    number: '02',
    navLabel: 'SBC',
    projects: [
      {
        id: 'sbc-1',
        name: 'Connecting the Digital Journey for Changi Airport Group',
        author: 'Ansh Kumar',
        role: 'Technical Consultant Intern',
        tag: 'Strategy',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: '',
        impact: 'High',
        desc: "Built a persona-driven personalization strategy with use cases that unifies Changi Airport's fragmented digital touchpoints using one customer profile, activated through Adobe's stack.",
        link: '',
        tags: [],
      },
      {
        id: 'sbc-2',
        name: 'Resume Screening Assistant',
        author: 'Manoshi Raha, Ansh Kumar, Abhinav Kumar',
        role: 'Technical Consultant Intern',
        tag: 'AI-Assisted',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: '',
        impact: 'High',
        desc: '',
        link: 'https://adobe-my.sharepoint.com/:p:/r/personal/abhinavkumar_adobe_com/Documents/Microsoft%20Teams%20Chat%20Files/Adobe_SBC_Resume_Agent_Deck%20(1).pptx',
        tags: [],
      },
    ],
  },
  {
    id: 'team-cjm',
    label: 'Team 06',
    number: '00',
    navLabel: 'CJM',
    projects: [
      {
        id: 'cjm-1',
        name: 'Email Regression Test Platform',
        author: 'Avinash Chaturvedi',
        role: 'Technical Consultant Intern',
        tag: 'QA Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Next.js, TypeScript, Tailwind, shadcn, Node, Express, Postgres, Prisma',
        impact: 'High',
        desc: 'An internal QA tool that validates email rendering and content stay stable across releases: same input, same output. Flows through Suite → Test → Baseline Case → Baseline Version, running the payload, fetching the inbox, and comparing against baseline (visual/DOM/style/a11y) with severity scoring and human review before promotion.',
        link: 'https://github.com/gigeorge_adobe/autoTestBot-X',
        tags: [],
      },
      {
        id: 'cjm-2',
        name: 'AJO QA Validator',
        author: 'Avinash Chaturvedi, Awani Mahesh Vaidya',
        role: 'Technical Consultant Intern',
        tag: 'QA Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Node, TypeScript, Playwright, React, SQLite, Prisma, Azure OpenAI',
        impact: 'High',
        desc: 'A QA automation tool for Adobe Journey Optimizer (AJO) that authenticates via browser session, pulls journey definitions, validates them against BRD/TSD specs, and drives live test-mode simulations in the AJO canvas, backed by an LLM-powered validation pipeline.',
        link: 'https://github.com/gigeorge_adobe/autoTestBot-X',
        tags: [],
      },
    ],
  },
];

export const AVATAR_COLORS = [
  { bg: 'rgba(225,37,27,0.2)', color: '#e1251b' },
  { bg: 'rgba(37,99,235,0.2)', color: '#60a5fa' },
  { bg: 'rgba(5,150,105,0.2)', color: '#34d399' },
  { bg: 'rgba(217,119,6,0.2)', color: '#fbbf24' },
  { bg: 'rgba(139,92,246,0.2)', color: '#a78bfa' },
  { bg: 'rgba(236,72,153,0.2)', color: '#f472b6' },
] as const;