import { Team } from './types';

export const TEAMS: Team[] = [
  {
    id: 'team-ui',
    label: 'Team 01',
    number: '03',
    navLabel: 'UI',
    projects: [
      {
        id: 'ui-1',
        name: 'Nirmit',
        author: 'Achindra Sharma',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Typescript, Python FastAPI',
        impact: 'High',
        desc: 'Nirmit is a culturally-aware design partner that bridges the gap between expensive professional firms and local contractors for Indian homeowners. By understanding the nuances of Indian domestic life, it transforms a simple conversation into personalized, 3D room visions that users can refine through natural dialogue. The experience provides instant cost clarity and a detailed execution plan, making high-quality, custom home design accessible and achievable.',
        tags: [],
      },
      {
        id: 'ui-2',
        name: 'FinPath - AI Financial Planner',
        author: 'Daniel Paul',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Typescript, Python FastAPI',
        impact: 'High',
        desc: 'FinPath is a personal finance app that helps users track their income and expenses, set and allocate financial goals with auto-generated month-by-month plans, simulate debt payoff using avalanche or snowball strategies, visualize cash flow , monitor their financial health with a composite score, explore what-if scenarios, and chat with an AI assistant named Penny for financial insights.',
        tags: [],
      },
      {
        id: 'ui-3',
        name: 'Lume Corp',
        author: 'Shreeya Bajpai',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Javascript',
        impact: 'High',
        desc: 'An AI-integrated corporate event planning platform designed for an immersive experience of the planning flow, with 2D setup visualiser.',
        tags: [],
      },
    ],
  },
  {
    id: 'team-data',
    label: 'Team 02',
    number: '01',
    navLabel: 'DATA',
    projects: [
      {
        id: 'data-1',
        name: 'AEP QueryGen',
        author: 'Anamaya Saraogi, Kanika Jain',
        role: 'Technical Consultant Intern',
        tag: 'Visualization',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python FastAPI, React',
        impact: 'High',
        desc: 'Built a utility tool leveraging LLM and RAG to automate segment validation on Adobe Experience Platform, significantly reducing manual effort.',
        tags: [],
      },
    ],
  },
  {
    id: 'team-workfront',
    label: 'Team 03',
    number: '02',
    navLabel: 'WORKFRONT',
    projects: [
      {
        id: 'wf-1',
        name: 'Audit Automation',
        author: 'Namratha R',
        role: 'Technical Consultant Intern',
        tag: 'Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Workfront Core, Workfront Fusion, Claude (LLM), Webhooks, JSON Processing, Prompt Engineering, Reporting and Canvas Dashobard',
        impact: 'Critical',
        desc: 'Developed an AI-powered Audit Automation solution to automate audit assessments, gap identification, risk analysis, escalation tracking, action item generation, and project RAG reporting. The platform transforms audit conversations into structured deliverables, findings, recommendations, and executive dashboard insights for governance and portfolio visibility. ',
        tags: [],
      },
      {
        id: 'wf-2',
        name: 'IntelliMatch AI',
        author: 'Sachin D.',
        role: 'Technical Consultant Intern',
        tag: 'Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: ' Ollama (Local LLM Runtime), Mistral (LLM Model), SBERT DL Model, Python FastAPI, JSON Data Pipelines, Workfront Core, Workfront Fusion, Ngrok, Streamlit, HTML',
        impact: 'Critical',
        desc: 'A hybrid agentic system for intelligent project allocation and workforce decisions, that brings decision intelligence to project allocation, enabling structured, explainable, and data-driven staffing decisions.',
        tags: [],
      },
    ],
  },
  {
    id: 'team-content',
    label: 'Team 04',
    number: '02',
    navLabel: 'CONTENT',
    projects: [
      {
        id: 'ct-1',
        name: 'Adokicks',
        author: 'A R Rajeev Chandar',
        role: 'Technical Consultant Intern',
        tag: 'AI-Assisted',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'EDS, HTML, CSS, Javascript',
        impact: 'High',
        desc: 'AdoKicks is a modern e-commerce footwear platform built using Adobe Experience Manager and Edge Delivery Services principles to deliver a fast, scalable, and seamless shopping experience.',
        tags: [],
      },
      {
        id: 'ct-2',
        name: 'Global Translation Pipeline',
        author: 'Sudeepa Santhanam',
        role: 'Technical Consultant Intern',
        tag: 'Localization',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'EDS, HTML, CSS, Javascript',
        impact: 'Critical',
        desc: 'Automated localization pipeline for Adobe marketing content, supporting 26 languages with human-in-the-loop review for high-sensitivity strings.',
        tags: [],
      },
    ],
  },
  {
    id: 'team-dacoe',
    label: 'Team 05',
    number: '02',
    navLabel: 'DACoE',
    projects: [
      {
        id: 'pl-1',
        name: 'Retail Insight Orchestrator',
        author: 'Shambhavi Sinha',
        role: 'Technical Consultant Intern',
        tag: 'Performance',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python, AEP',
        impact: 'Critical',
        desc: "This project is a retail insight orchestration layer built on top of Customer Journey Analytics (via CJA MCP). It takes a business question in natural language, understands the retail intent, maps it to the right metrics and dimensions, and generates a structured analysis workflow instead of making the user manually figure out what to ask.",
        tags: [],
      },
      {
        id: 'pl-2',
        name: 'Agent Evaluation Harness',
        author: 'Yanish Rai',
        role: 'Technical Consultant Intern',
        tag: 'Developer Tools',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python, React',
        impact: 'High',
        desc: `Given (a) an AEP dataset and (b) a set of business use cases, automatically generates a tiered prompt suite for the Data Insights Agent, executes those prompts against the live agent in AEP, computes the ground-truth answer directly from the underlying data, scores the agent's responses against ground truth, and produces a reliability report with failure mode analysis.`,
        tags: [],
      },
    ],
  },
  {
    id: 'team-cjm',
    label: 'Team 06',
    number: '00',
    navLabel: 'CJM',
    projects: [
      {
        id: 'pl-1',
        name: '---',
        author: '---',
        role: 'Technical Consultant Intern',
        tag: 'Performance',
        status: 'In Progress',
        timeline: 'May – Jul 2026',
        stack: '--',
        impact: 'Critical',
        desc: "----",
        tags: [],
      },
    ],
  },
];

export const AVATAR_COLORS = [
  { bg: 'rgba(225,37,27,0.2)', color: '#e1251b' },
  { bg: 'rgba(37,99,235,0.2)', color: '#60a5fa' },
  { bg: 'rgba(5,150,105,0.2)', color: '#34d399' },
  { bg: 'rgba(217,119,6,0.2)', color: '#fbbf24' },
  { bg: 'rgba(139,92,246,0.2)', color: '#a78bfa' },
  { bg: 'rgba(236,72,153,0.2)', color: '#f472b6' },
] as const;