import { Team } from './types';

export const TEAMS: Team[] = [
  {
    id: 'team-ui',
    label: 'Team 01',
    number: '03',
    navLabel: 'UI',
    projects: [
      {
        id: 'ui-1',
        name: 'Nirmit',
        author: 'Achindra Sharma',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Typescript',
        impact: 'High',
        desc: 'Nirmit is a culturally-aware design partner that bridges the gap between expensive professional firms and local contractors for Indian homeowners. By understanding the nuances of Indian domestic life, it transforms a simple conversation into personalized, 3D room visions that users can refine through natural dialogue. The experience provides instant cost clarity and a detailed execution plan, making high-quality, custom home design accessible and achievable.',
        tags: ['Figma', 'Prototyping', 'User Testing', 'Design System'],
      },
      {
        id: 'ui-2',
        name: 'FinPath - AI Financial Planner',
        author: 'Daniel Paul',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Tokens Studio, CSS',
        impact: 'Critical',
        desc: 'FinPath is a personal finance app that helps users track their income and expenses, set and allocate financial goals with auto-generated month-by-month plans, simulate debt payoff using avalanche or snowball strategies, visualize cash flow , monitor their financial health with a composite score, explore what-if scenarios, and chat with an AI assistant named Penny for financial insights.',
        tags: ['Tokens', 'WCAG', 'Automation'],
      },
      {
        id: 'ui-3',
        name: 'Lume Corp',
        author: 'Shreeya Bajpai',
        role: 'Technical Consultant Intern',
        tag: 'UI',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'React, Javascript',
        impact: 'High',
        desc: 'An AI-integrated corporate event planning platform designed for an immersive experience of the planning flow, with 2D setup visualiser.',
        tags: ['React', 'Storybook', 'Spectrum', 'CSS'],
      },
      // {
      //   id: 'ui-4',
      //   name: 'Onboarding Flow Redesign',
      //   author: 'Kai Okafor',
      //   role: 'Product Design Intern',
      //   tag: 'UX',
      //   status: 'In Review',
      //   timeline: 'Jun – Jul 2026',
      //   stack: 'Figma, Maze',
      //   impact: 'Medium',
      //   desc: 'Redesigning the first-time user onboarding flow for Adobe Express, tested with 120 participants. New flow reduces time-to-first-creation from 8 minutes to 2.4 minutes.',
      //   tags: ['Onboarding', 'Express', 'Research'],
      // },
    ],
  },
  {
    id: 'team-data',
    label: 'Team 02',
    number: '01',
    navLabel: 'DATA',
    projects: [
      {
        id: 'data-1',
        name: 'AEP Utility Tool',
        author: 'Anamaya Saraogi, Kanika Jain',
        role: 'Technical Consultant Intern',
        tag: 'Visualization',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python',
        impact: 'High',
        desc: 'Worked with internal and external APIs to build and integrate scalable features. Developed a utility to enhance segment validation on Adobe Experience Platform.',
        tags: ['D3.js', 'Python', 'ML', 'Dashboard'],
      },
    ],
  },
  {
    id: 'team-workfront',
    label: 'Team 03',
    number: '02',
    navLabel: 'WORKFRONT',
    projects: [
      {
        id: 'wf-1',
        name: 'Smart Audit Request Management System',
        author: 'Namratha R',
        role: 'Technical Consultant Intern',
        tag: 'Automation',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Java, Kubernetes',
        impact: 'Critical',
        desc: 'A rule-based automation engine for Workfront that allows project managers to define conditional workflow triggers, reducing manual task assignment by an estimated 60%.',
        tags: ['Java', 'K8s', 'Automation', 'Workflow'],
      },
      // {
      //   id: 'wf-2',
      //   name: 'Resource Load Balancer',
      //   author: 'Tom Müller',
      //   role: 'Product Engineering Intern',
      //   tag: 'Resource Mgmt',
      //   status: 'In Review',
      //   timeline: 'Jun – Jul 2026',
      //   stack: 'TypeScript, GraphQL',
      //   impact: 'High',
      //   desc: 'Intelligent resource allocation tool that analyzes team capacity and project deadlines to surface over-allocation risks and suggest rebalancing options.',
      //   tags: ['GraphQL', 'TypeScript', 'Resource Planning'],
      // },
    ],
  },
  {
    id: 'team-content',
    label: 'Team 04',
    number: '02',
    navLabel: 'CONTENT',
    projects: [
      {
        id: 'ct-1',
        name: 'Adokicks',
        author: 'A R Rajeev Chandar',
        role: 'Technical Consultant Intern',
        tag: 'AI-Assisted',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Claude API, Next.js',
        impact: 'High',
        desc: 'AdoKicks is a modern e-commerce footwear platform built using Adobe Experience Manager and Edge Delivery Services principles to deliver a fast, scalable, and seamless shopping experience.',
        tags: ['AI', 'Claude API', 'Next.js', 'Content Strategy'],
      },
      {
        id: 'ct-2',
        name: 'Global Translation Pipeline',
        author: 'Sudeepa Santhanam',
        role: 'Technical Consultant Intern',
        tag: 'Localization',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Python, Phrase TMS',
        impact: 'Critical',
        desc: 'Automated localization pipeline for Adobe marketing content, supporting 26 languages with human-in-the-loop review for high-sensitivity strings.',
        tags: ['Localization', 'Python', 'i18n', 'Translation'],
      },
    ],
  },
  {
    id: 'team-dacoe',
    label: 'Team 05',
    number: '02',
    navLabel: 'DACoE',
    projects: [
      {
        id: 'pl-1',
        name: 'DIA prompt library',
        author: 'Shambhavi Sinha',
        role: 'Technical Consultant Intern',
        tag: 'Performance',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Cloudflare Workers, Rust',
        impact: 'Critical',
        desc: "Optimizing Adobe's global CDN edge configuration using Cloudflare Workers, achieving 40% reduction in global P95 latency for static asset delivery.",
        tags: ['CDN', 'Edge Computing', 'Rust', 'Cloudflare'],
      },
      {
        id: 'pl-2',
        name: 'Agent Evaluation Harness',
        author: 'Yanish Rai',
        role: 'Technical Consultant Intern',
        tag: 'Developer Tools',
        status: 'Completed',
        timeline: 'Apr – Jun 2026',
        stack: 'Next.js, Contentful',
        impact: 'High',
        desc: `Given (a) an AEP dataset and (b) a set of business use cases, automatically generates a tiered prompt suite for the Data Insights Agent, executes those prompts against the live agent in AEP, computes the ground-truth answer directly from the underlying data, scores the agent's responses against ground truth, and produces a reliability report with failure mode analysis.`,
        tags: ['Next.js', 'Developer Experience', 'Docs', 'Search'],
      },
      // {
      //   id: 'pl-3',
      //   name: 'Auth0 Migration',
      //   author: 'Marcus Webb',
      //   role: 'Security Intern',
      //   tag: 'Security',
      //   status: 'Completed',
      //   timeline: 'May – Jul 2026',
      //   stack: 'Auth0, TypeScript',
      //   impact: 'Critical',
      //   desc: 'Platform-wide migration of authentication services to Auth0, consolidating 12 separate auth implementations and enabling Universal Login across all Adobe web properties.',
      //   tags: ['Auth0', 'Security', 'SSO', 'TypeScript'],
      // },
      // {
      //   id: 'pl-4',
      //   name: 'Observability Stack v2',
      //   author: 'Hina Tanaka',
      //   role: 'SRE Intern',
      //   tag: 'Observability',
      //   status: 'In Progress',
      //   timeline: 'Jun – Aug 2026',
      //   stack: 'OpenTelemetry, Grafana',
      //   impact: 'High',
      //   desc: 'Upgrading the platform observability stack to OpenTelemetry standards, adding distributed tracing across 80+ microservices with custom Grafana dashboards.',
      //   tags: ['OpenTelemetry', 'Grafana', 'Tracing', 'SRE'],
      // },
      // {
      //   id: 'pl-5',
      //   name: 'CI/CD Pipeline Templates',
      //   author: 'Ben Osei',
      //   role: 'DevOps Intern',
      //   tag: 'DevOps',
      //   status: 'Completed',
      //   timeline: 'Jun – Jul 2026',
      //   stack: 'GitHub Actions, Terraform',
      //   impact: 'Medium',
      //   desc: 'Standardized CI/CD pipeline templates for Adobe engineering teams, reducing pipeline setup time from days to under 30 minutes while enforcing security scanning and testing gates.',
      //   tags: ['GitHub Actions', 'Terraform', 'DevOps', 'Templates'],
      // },
      // {
      //   id: 'pl-6',
      //   name: 'Cost Attribution Dashboard',
      //   author: 'Mei Lin',
      //   role: 'FinOps Intern',
      //   tag: 'FinOps',
      //   status: 'In Review',
      //   timeline: 'Jun – Aug 2026',
      //   stack: 'AWS Cost Explorer, Looker',
      //   impact: 'High',
      //   desc: 'A FinOps dashboard that attributes cloud infrastructure costs to product teams and features, enabling data-driven infrastructure investment decisions.',
      //   tags: ['AWS', 'FinOps', 'Cost Management', 'Looker'],
      // },
    ],
  },
];

export const AVATAR_COLORS = [
  { bg: 'rgba(225,37,27,0.2)', color: '#e1251b' },
  { bg: 'rgba(37,99,235,0.2)', color: '#60a5fa' },
  { bg: 'rgba(5,150,105,0.2)', color: '#34d399' },
  { bg: 'rgba(217,119,6,0.2)', color: '#fbbf24' },
  { bg: 'rgba(139,92,246,0.2)', color: '#a78bfa' },
  { bg: 'rgba(236,72,153,0.2)', color: '#f472b6' },
] as const;